

DROP TABLE IF EXISTS Applicant;
DROP TABLE IF EXISTS ApplicantApplication;
DROP TABLE IF EXISTS ApplicantInfor;
DROP TABLE IF EXISTS Charact;
DROP TABLE IF EXISTS ContactOfAppli;
DROP TABLE IF EXISTS Document;
DROP TABLE IF EXISTS Funding;
DROP TABLE IF EXISTS Insitution;
DROP TABLE IF EXISTS InstitutionFundAppli;
DROP TABLE IF EXISTS InstututionManangement;
DROP TABLE IF EXISTS Mananger;
DROP TABLE IF EXISTS Nationality;
DROP TABLE IF EXISTS Status;